# Generated by Django 5.2.17 on 2026-09-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_notafiscal_produto_itemnota'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
    ]
