# Generated by Django 5.2.17 on 2026-09-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_fornecedor_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='endereco',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='rua',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
