# Generated by Django 5.2.17 on 2026-09-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
